export const COMMODITIES = [
  // ===================
  // RICE
  // ===================

  // ── Local Rice (no grain type, straight to size) ──
  {
    sku: "RIC-LOC-B1",
    category: "Rice",
    brand: null,
    price: 100000,
    unit: "kg",
    size: 50,
    name: "Local rice",
    image: "/rice.jpg",
    description: "Local rice (1 bag)",
  },
  {
    sku: "RIC-LOC-B0.5",
    category: "Rice",
    brand: null,
    price: 50000,
    unit: "kg",
    size: 25,
    name: "Local rice",
    image: "/rice.jpg",
    description: "Local rice (half bag)",
  },
  {
    sku: "RIC-LOC-B0.25",
    category: "Rice",
    brand: null,
    price: 25000,
    unit: "kg",
    size: 12.5,
    name: "Local rice",
    image: "/rice.jpg",
    description: "Local rice (quarter bag)",
  },

  // ── Foreign Rice — Long Grain ──
  {
    sku: "RIC-FOR-LG-B1",
    category: "Rice",
    brand: null,
    price: 100000,
    unit: "kg",
    size: 50,
    name: "Long grain foreign rice",
    image: "/rice.jpg",
    description: "Long grain foreign rice (1 bag)",
  },
  {
    sku: "RIC-FOR-LG-B0.5",
    category: "Rice",
    brand: null,
    price: 50000,
    unit: "kg",
    size: 25,
    name: "Long grain foreign rice",
    image: "/rice.jpg",
    description: "Long grain foreign rice (half bag)",
  },
  {
    sku: "RIC-FOR-LG-B0.25",
    category: "Rice",
    brand: null,
    price: 25000,
    unit: "kg",
    size: 12.5,
    name: "Long grain foreign rice",
    image: "/rice.jpg",
    description: "Long grain foreign rice (quarter bag)",
  },

  // ── Foreign Rice — Short Grain ──
  {
    sku: "RIC-FOR-SG-B1",
    category: "Rice",
    brand: null,
    price: 100000,
    unit: "kg",
    size: 50,
    name: "Short grain foreign rice",
    image: "/rice.jpg",
    description: "Short grain foreign rice (1 bag)",
  },
  {
    sku: "RIC-FOR-SG-B0.5",
    category: "Rice",
    brand: null,
    price: 50000,
    unit: "kg",
    size: 25,
    name: "Short grain foreign rice",
    image: "/rice.jpg",
    description: "Short grain foreign rice (half bag)",
  },
  {
    sku: "RIC-FOR-SG-B0.25",
    category: "Rice",
    brand: null,
    price: 25000,
    unit: "kg",
    size: 12.5,
    name: "Short grain foreign rice",
    image: "/rice.jpg",
    description: "Short grain foreign rice (quarter bag)",
  },

  // =====================
  // BEANS
  // =====================

  // ── Oloyin Beans (Brown) ──
  {
    sku: "BEA-OLY-B1",
    category: "Beans",
    brand: null,
    price: 100000,
    unit: "kg",
    size: 50,
    name: "Oloyin beans (Brown)",
    image: "/Olotu beans.jpg",
    description: "Oloyin beans (1 bag)",
  },
  {
    sku: "BEA-OLY-B0.5",
    category: "Beans",
    brand: null,
    price: 50000,
    unit: "kg",
    size: 25,
    name: "Oloyin beans (Brown)",
    image: "/Olotu beans.jpg",
    description: "Oloyin beans (half bag)",
  },
  {
    sku: "BEA-OLY-B0.25",
    category: "Beans",
    brand: null,
    price: 25000,
    unit: "kg",
    size: 12.5,
    name: "Oloyin beans (Brown)",
    image: "/Olotu beans.jpg",
    description: "Oloyin beans (quarter bag)",
  },

  // ── White Beans ──
  {
    sku: "BEA-WHT-B1",
    category: "Beans",
    brand: null,
    price: 100000,
    unit: "kg",
    size: 50,
    name: "White beans",
    image: "/Sokoto Beans.png",
    description: "White beans (1 bag)",
  },
  {
    sku: "BEA-WHT-B0.5",
    category: "Beans",
    brand: null,
    price: 50000,
    unit: "kg",
    size: 25,
    name: "White beans",
    image: "/Sokoto Beans.png",
    description: "White beans (half bag)",
  },
  {
    sku: "BEA-WHT-B0.25",
    category: "Beans",
    brand: null,
    price: 25000,
    unit: "kg",
    size: 12.5,
    name: "White beans",
    image: "/Sokoto Beans.png",
    description: "White beans (quarter bag)",
  },

  // =====================
  // GARRI — Commented out (pending market run)
  // =====================
  // {
  //   sku: "GAR-YEL-B1",
  //   category: "Garri",
  //   brand: null,
  //   price: 100000,
  //   unit: "kg",
  //   size: 50,
  //   name: "Yellow garri",
  //   image: "/Yellow garri.webp",
  //   description: "Yellow garri (1 bag)",
  // },
  // {
  //   sku: "GAR-YEL-B0.5",
  //   category: "Garri",
  //   brand: null,
  //   price: 50000,
  //   unit: "kg",
  //   size: 25,
  //   name: "Yellow garri",
  //   image: "/Yellow garri.webp",
  //   description: "Yellow garri (half bag)",
  // },
  // {
  //   sku: "GAR-YEL-B0.25",
  //   category: "Garri",
  //   brand: null,
  //   price: 25000,
  //   unit: "kg",
  //   size: 12.5,
  //   name: "Yellow garri",
  //   image: "/Yellow garri.webp",
  //   description: "Yellow garri (quarter bag)",
  // },
  // {
  //   sku: "GAR-WHT-B1",
  //   category: "Garri",
  //   brand: null,
  //   price: 100000,
  //   unit: "kg",
  //   size: 50,
  //   name: "White garri",
  //   image: "/Garri-2.jpg",
  //   description: "White garri (Ijebu - 1 bag)",
  // },
  // {
  //   sku: "GAR-WHT-B0.5",
  //   category: "Garri",
  //   brand: null,
  //   price: 50000,
  //   unit: "kg",
  //   size: 25,
  //   name: "White garri",
  //   image: "/Garri-2.jpg",
  //   description: "White garri (Ijebu - half bag)",
  // },
  // {
  //   sku: "GAR-WHT-B0.25",
  //   category: "Garri",
  //   brand: null,
  //   price: 25000,
  //   unit: "kg",
  //   size: 12.5,
  //   name: "White garri",
  //   image: "/Garri-2.jpg",
  //   description: "White garri (Ijebu - quarter bag)",
  // },
];
